import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { API } from "@/services/endpoints/apiendpoint";
import Axiosintance from "@/services/axios/axiosInterceptor";
export default function Home() {
  const router = useRouter()

  useEffect(() => {
    router.push("/auth/register/phone")
  }, []);

  return (
    <>
      <Head>
        <title>E-Pay Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
